name: Generate Swagger.json
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: example.org
      EXPORT_SWAGGER_FILE: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          cache: 'pip'
          python-version: 3.10.2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install packages
        run: pip install -r backend/requirements.txt
      - name: Generate Swagger UI
        run: |
          git clone https://github.com/drdeee/swagger-template
          rm -r ./swagger-template/.git
          python backend/backend/app.py > ./swagger-template/swagger.json
      - name: Log swagger.json
        run: cat ./swagger-template/swagger.json
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-template
